# This is a config for E2B sandbox template.
# You can use template ID (5pg2x2yuft3bg6q6wy73) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("5pg2x2yuft3bg6q6wy73") # Sync sandbox
# sandbox = await AsyncSandbox.create("5pg2x2yuft3bg6q6wy73") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('5pg2x2yuft3bg6q6wy73')

team_id = "3c86ebda-7e0f-4668-9f29-f11cccf424ff"
start_cmd = "/root/.jupyter/start-up.sh"
dockerfile = "e2b.Dockerfile"
template_id = "5pg2x2yuft3bg6q6wy73"
